# Generated by Django 5.0.7 on 2024-07-12 18:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('encuesta', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CapituloI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('edad', models.IntegerField()),
                ('sexo', models.CharField(choices=[('M', 'Masculino'), ('F', 'Femenino')], default='M', max_length=1)),
                ('viaja_con', models.CharField(choices=[('S', 'Solo'), ('A', 'Amigos'), ('T', 'Compañeros de trabajo'), ('F', 'Familia'), ('O', 'Otro')], max_length=1)),
                ('viaja_con_otro', models.CharField(blank=True, max_length=100, null=True)),
                ('numero_personas', models.IntegerField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CapituloII',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('motivo_viaje', models.CharField(choices=[('1', 'Visita a familiares o amigos'), ('2', 'Vacaciones (recreación, ocio, sol y playa)'), ('3', 'Compras'), ('4', 'Turismo Cultural'), ('5', 'Asistencia a eventos artísticos'), ('6', 'Estudio y/o formación'), ('7', 'Tratamiento de salud y belleza'), ('8', 'Religioso'), ('9', 'Asistencia a Congresos, Seminarios, convenciones'), ('10', 'Trabajo remunerado en destino'), ('11', 'Trabajo o negocios (no remunerado en destino)'), ('12', 'Participación en eventos artísticos y/o deportivos'), ('13', 'Tránsito'), ('14', 'Otro')], max_length=2)),
                ('motivo_viaje_otro', models.CharField(blank=True, max_length=100, null=True)),
                ('organizacion_viaje_otro', models.CharField(blank=True, max_length=100, null=True)),
                ('transporte_interno_otro', models.CharField(blank=True, max_length=100, null=True)),
                ('otro_servicio', models.CharField(blank=True, max_length=100, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CapituloIII',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gasto_paquete_turistico', models.BooleanField()),
                ('valor_paquete_usted', models.DecimalField(decimal_places=2, max_digits=10)),
                ('valor_paquete_terceros_no_grupo', models.DecimalField(decimal_places=2, max_digits=10)),
                ('valor_paquete_terceros_si_grupo', models.DecimalField(decimal_places=2, max_digits=10)),
                ('personas_paquete', models.IntegerField()),
                ('gasto_transporte_internacional', models.BooleanField()),
                ('valor_transporte_usted', models.DecimalField(decimal_places=2, max_digits=10)),
                ('valor_transporte_terceros_no_grupo', models.DecimalField(decimal_places=2, max_digits=10)),
                ('valor_transporte_terceros_si_grupo', models.DecimalField(decimal_places=2, max_digits=10)),
                ('personas_transporte', models.IntegerField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Moneda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('codigo_divisa', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Nacionalidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='OrganizacionViaje',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Pais',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('codigo', models.CharField(max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='PaisVisita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('noches_vivienda_propia', models.IntegerField()),
                ('noches_hotel', models.IntegerField()),
                ('noches_vivienda_familiar_amigos', models.IntegerField()),
                ('noches_vivienda_alquiler', models.IntegerField()),
                ('noches_otro_tipo_vivienda', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='ServiciosPaquete',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=200)),
            ],
        ),
        migrations.DeleteModel(
            name='DestinationDetails',
        ),
        migrations.DeleteModel(
            name='GeneralInformation',
        ),
        migrations.DeleteModel(
            name='TripDetails',
        ),
        migrations.AddField(
            model_name='capituloiii',
            name='moneda_paquete_terceros_no_grupo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='moneda_paquete_terceros_no_grupo', to='encuesta.moneda'),
        ),
        migrations.AddField(
            model_name='capituloiii',
            name='moneda_paquete_terceros_si_grupo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='moneda_paquete_terceros_si_grupo', to='encuesta.moneda'),
        ),
        migrations.AddField(
            model_name='capituloiii',
            name='moneda_paquete_usted',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='moneda_paquete_usted', to='encuesta.moneda'),
        ),
        migrations.AddField(
            model_name='capituloiii',
            name='moneda_transporte_terceros_no_grupo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='moneda_transporte_terceros_no_grupo', to='encuesta.moneda'),
        ),
        migrations.AddField(
            model_name='capituloiii',
            name='moneda_transporte_terceros_si_grupo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='moneda_transporte_terceros_si_grupo', to='encuesta.moneda'),
        ),
        migrations.AddField(
            model_name='capituloiii',
            name='moneda_transporte_usted',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='moneda_transporte_usted', to='encuesta.moneda'),
        ),
        migrations.AddField(
            model_name='capituloi',
            name='nacionalidad',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='encuesta.nacionalidad'),
        ),
        migrations.AddField(
            model_name='capituloii',
            name='organizacion_viaje',
            field=models.ManyToManyField(to='encuesta.organizacionviaje'),
        ),
        migrations.AddField(
            model_name='capituloi',
            name='pais',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='encuesta.pais'),
        ),
        migrations.AddField(
            model_name='paisvisita',
            name='capitulo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='encuesta.capituloiii'),
        ),
        migrations.AddField(
            model_name='paisvisita',
            name='pais',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='encuesta.pais'),
        ),
        migrations.AddField(
            model_name='capituloiii',
            name='paises_visitados',
            field=models.ManyToManyField(through='encuesta.PaisVisita', to='encuesta.pais'),
        ),
        migrations.AddField(
            model_name='capituloii',
            name='servicios_paquete',
            field=models.ManyToManyField(to='encuesta.serviciospaquete'),
        ),
    ]
